String.defaultLocale = "es";
String.locale = "es";
String.toLocaleString({
	"zh": {
    "%game-intro"           : "加入 <strong>纸杯蛋糕!</strong>",
    "%restart-button"       : "重新开始",
    "%keep-playing-button"  : "继续游戏",
    "%retry-button"         : "重试",
    "%game-won"             : "你赢了!",
    "%game-over"            : "游戏结束!",
    "%game-explanation"     : "<strong class=\"important\">游戏规则:</strong> 使用你的 <strong>方向键</strong> 移动方块。当两个相同符号的方块接触时，它们会 <strong>合并升级!</strong>",
    "%disclaimer"           : "<strong class=\"important\">注意:</strong> 这个网站 <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> 是官方版本 <a href=\"http://git.io/2048\">2048</a> 的衍生版本，原作者是 <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>。",
    "%credits"              : "纸杯蛋糕图片来自 <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>。",
    "%tweet1"               : "我在2048纸杯蛋糕游戏中得分 \"",
    "%tweet2"               : " #2048game",
    "%tile-legend"          : "<strong class=\"important\">方块图例:</strong>",
    '%2'                    : '香草生日',
    '%4'                    : '泡泡糖粉',
    '%8'                    : '阳光香草',
    '%16'                   : '法芙娜白巧克力',
    '%32'                   : '巧克力花生酱芝士蛋糕',
    '%64'                   : '巧克力薄荷软糖',
    '%128'                  : '巧克力蜘蛛网',
    '%256'                  : '烤棉花糖',
    '%512'                  : '曲奇奶油',
    '%1024'                 : '巧克力圣代',
    '%2048'                 : '白巧克力薄荷',
    '%4096'                 : '2017五彩纸屑香草',
    '%8192'                 : '彩虹',
    '%p0'                   : '香草生日',
    '%p4'                   : '泡泡糖粉',
    '%p8'                   : '阳光香草',
    '%p16'                  : '法芙娜白巧克力',
    '%p32'                  : '巧克力花生酱芝士蛋糕',
    '%p64'                  : '巧克力薄荷软糖',
    '%p128'                 : '巧克力蜘蛛网',
    '%p256'                 : '烤棉花糖',
    '%p512'                 : '曲奇奶油',
    '%p1024'                : '巧克力圣代',
    '%p2048'                : '白巧克力薄荷',
    '%p4096'                : '2017五彩纸屑香草',
    '%p8192'                : '彩虹'
	},
  "en": {
    "%game-intro"           : "Join the <strong>Cupcakes!</strong>",
    "%restart-button"       : "New Game",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "Cupcakes images by <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-CUPCAKES #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'vanilla birthday',
    '%4'                    : 'bubblegum pink',
    '%8'                    : 'sunshine vanilla',
    '%16'                   : 'valrhona blonde ganache',
    '%32'                   : 'chocolare peanut butter cheesecake',
    '%64'                   : 'chocolate mint fudge',
    '%128'                  : 'chocolate spider web',
    '%256'                  : 'toasted marshmallow',
    '%512'                  : 'cookies and creme',
    '%1024'                 : 'chocolate sundae',
    '%2048'                 : 'white chocolate peppermint',
    '%4096'                 : '2017 Confetti Vanilla',
    '%8192'                 : 'Rainbow',
    '%p0'                   : 'vanilla birthday',
    '%p4'                   : 'bubblegum pink',
    '%p8'                   : 'sunshine vanilla',
    '%p16'                  : 'valrhona blonde ganache',
    '%p32'                  : 'choc. peanut butter cheesecake',
    '%p64'                  : 'choc. mint fudge',
    '%p128'                 : 'choc. spider web',
    '%p256'                 : 'toasted marshmallow',
    '%p512'                 : 'cookies and creme',
    '%p1024'                : 'choc. sundae',
    '%p2048'                : 'white choc. peppermint',
    '%p4096'                : '2017 Confetti Vanilla',
    '%p8192'                : 'Rainbow'
  },
"es": {
    "%game-intro"           : "¡Únete a los <strong>cupcakes</strong>!",
    "%restart-button"       : "Nueva partida",
    "%keep-playing-button"  : "Seguir",
    "%retry-button"         : "Reintentar",
    "%game-won"             : "¡Ganaste!",
    "%game-over"            : "¡Fin del juego!",
    "%game-explanation"     : "<strong class=\"important\">Cómo jugar:</strong> Usa las <strong>flechas</strong> para mover las fichas. Si dos fichas iguales se tocan, <strong>¡se fusionan!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "Cupcakes images by <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-CUPCAKES #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'vanilla birthday',
    '%4'                    : 'bubblegum pink',
    '%8'                    : 'sunshine vanilla',
    '%16'                   : 'valrhona blonde ganache',
    '%32'                   : 'chocolare peanut butter cheesecake',
    '%64'                   : 'chocolate mint fudge',
    '%128'                  : 'chocolate spider web',
    '%256'                  : 'toasted marshmallow',
    '%512'                  : 'cookies and creme',
    '%1024'                 : 'chocolate sundae',
    '%2048'                 : 'white chocolate peppermint',
    '%4096'                 : '2017 Confetti Vanilla',
    '%8192'                 : 'Rainbow',
    '%p0'                   : 'vanilla birthday',
    '%p4'                   : 'bubblegum pink',
    '%p8'                   : 'sunshine vanilla',
    '%p16'                  : 'valrhona blonde ganache',
    '%p32'                  : 'choc. peanut butter cheesecake',
    '%p64'                  : 'choc. mint fudge',
    '%p128'                 : 'choc. spider web',
    '%p256'                 : 'toasted marshmallow',
    '%p512'                 : 'cookies and creme',
    '%p1024'                : 'choc. sundae',
    '%p2048'                : 'white choc. peppermint',
    '%p4096'                : '2017 Confetti Vanilla',
    '%p8192'                : 'Rainbow'
  }
});
